# Generated by Django 3.2.5 on 2021-10-26 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Completion_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commencement_date', models.DateTimeField(default=datetime.datetime(2021, 10, 26, 10, 38, 17, 136868, tzinfo=utc))),
                ('completion_date', models.DateTimeField(default=datetime.datetime(2021, 10, 26, 10, 38, 17, 136884, tzinfo=utc))),
                ('completion_result', models.CharField(choices=[('E', 'ENROLLED'), ('N', 'NOT YET COMPLETE'), ('Q', 'CANCELLED'), ('C', 'COMPLETE')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=50)),
                ('course_bio', models.TextField()),
                ('course_img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_reach', models.IntegerField()),
                ('participation_target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('constraned_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('WA', 'WESTERN AUST'), ('QLD', 'QUEENSLAND'), ('NT', 'NORTHERN TERRITORY'), ('ACT', 'AUST CAPITAL TERRITORY'), ('SA', 'SOUTH AUST'), ('NSW', 'NEW SOUTH WALES'), ('VIC', 'VICTORIA'), ('EXT', 'EXTERNAL TERRITORIES')], max_length=5)),
                ('region', models.CharField(max_length=300)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-Binary'), ('O', 'Other')], max_length=5)),
                ('home_location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('profile_pic', models.URLField()),
                ('bio', models.TextField()),
                ('tech_life_balance', models.CharField(max_length=30)),
                ('in_mentor', models.CharField(max_length=30)),
                ('industry', models.CharField(choices=[('M', 'MINING'), ('AG', 'AGRICULTURE'), ('MN', 'MINING'), ('MF', 'MANUFACTURING'), ('UT', 'UTILITIES'), ('CS', 'CONSTRUCTION'), ('AR', 'ARTS AND RECREATION'), ('HC', 'HEALTH CARE'), ('ED', 'EDUCATION AND TRAINING'), ('PS', 'PROFESSIONAL SERVICES'), ('RE', 'REAL ESTATE'), ('TA', 'TOURISM AND ACCOMMODATION'), ('IT', 'INFORMATION AND MEDIA'), ('OT', 'OTHER')], max_length=50)),
                ('language', models.ManyToManyField(to='swc.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=50)),
                ('logo_url', models.URLField()),
                ('sponsor_tier', models.CharField(choices=[('PL', 'PLATNIUM'), ('G', 'GOLD'), ('S', 'SILVER'), ('B', 'BRONZE')], max_length=5)),
                ('sponsor_why', models.CharField(max_length=500)),
                ('sponsor_industry', models.CharField(choices=[('M', 'MINING'), ('AG', 'AGRICULTURE'), ('MN', 'MINING'), ('MF', 'MANUFACTURING'), ('UT', 'UTILITIES'), ('CS', 'CONSTRUCTION'), ('AR', 'ARTS AND RECREATION'), ('HC', 'HEALTH CARE'), ('ED', 'EDUCATION AND TRAINING'), ('PS', 'PROFESSIONAL SERVICES'), ('RE', 'REAL ESTATE'), ('TA', 'TOURISM AND ACCOMMODATION'), ('IT', 'INFORMATION AND MEDIA'), ('OT', 'OTHER')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.completion_status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.course')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.location')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.participant')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.IntegerField()),
                ('support_tech_women', models.IntegerField()),
                ('wider_tech_commitments', models.IntegerField()),
                ('sponsor', models.ManyToManyField(to='swc.Sponsors')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 10, 26, 10, 38, 17, 137615, tzinfo=utc))),
                ('course', models.ManyToManyField(to='swc.Course')),
                ('language', models.ManyToManyField(to='swc.Language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.location')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('better_equipped', models.IntegerField()),
                ('more_confident', models.IntegerField()),
                ('pursue_tech_career', models.IntegerField()),
                ('another_course', models.IntegerField()),
                ('interested_mentor', models.IntegerField()),
                ('course', models.ManyToManyField(to='swc.Course')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.participant')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ManyToManyField(to='swc.Language'),
        ),
    ]
