# Generated by Django 3.2.5 on 2021-10-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-Binary'), ('O', 'Other')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.AddField(
            model_name='schedule',
            name='course',
            field=models.ManyToManyField(to='swc.Course'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='language',
        ),
        migrations.AddField(
            model_name='schedule',
            name='language',
            field=models.ManyToManyField(to='swc.Language'),
        ),
    ]
