# Generated by Django 3.2.5 on 2021-10-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0003_auto_20211027_1628'),
        ('swc', '0003_auto_20211027_1815'),
    ]

    operations = [
    ]
