# Generated by Django 3.2.5 on 2021-10-28 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0003_auto_20211027_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='learnerpath',
            field=models.ManyToManyField(through='swc.StudentCourse', to='swc.Course'),
        ),
        migrations.AlterField(
            model_name='completion_status',
            name='commencement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 2, 10, 5, 629421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='completion_status',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 2, 10, 5, 629438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 2, 10, 5, 630175, tzinfo=utc)),
        ),
    ]
