# Generated by Django 3.2.5 on 2021-10-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0003_remove_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(default='not specified', max_length=30),
            preserve_default=False,
        ),
    ]
