# Generated by Django 3.2.5 on 2021-10-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0004_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=300),
        ),
    ]
