# Generated by Django 3.2.5 on 2021-10-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0004_auto_20211028_0210'),
        ('swc', '0004_merge_0003_auto_20211027_1628_0003_auto_20211027_1815'),
    ]

    operations = [
    ]
