# Generated by Django 3.2.5 on 2021-10-30 03:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0005_merge_20211030_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion_status',
            name='commencement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 3, 57, 45, 439930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='completion_status',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 3, 57, 45, 439944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 3, 57, 45, 440670, tzinfo=utc)),
        ),
    ]
