# Generated by Django 3.2.5 on 2021-11-01 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0006_auto_20211030_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='profile_pic',
            field=models.URLField(default='https://rachelburford.github.io/images/4.png'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completion_status',
            name='commencement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 3, 29, 21, 51431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='completion_status',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 3, 29, 21, 51431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 3, 29, 21, 52429, tzinfo=utc)),
        ),
    ]
