# Generated by Django 3.2.5 on 2021-11-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0005_auto_20211101_1144'),
        ('swc', '0006_auto_20211030_0357'),
    ]

    operations = [
    ]
