# Generated by Django 3.2.5 on 2021-10-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0006_auto_20211016_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('WA', 'WESTERN AUST'), ('QLD', 'QUEENSLAND'), ('NT', 'NORTHERN TERRITORY'), ('ACT', 'AUST CAPITAL TERRITORY'), ('SA', 'SOUTH AUST'), ('NSW', 'NEW SOUTH WALES'), ('VIC', 'VICTORIA'), ('EXT', 'EXTERNAL TERRITORIES')], max_length=5),
        ),
    ]
