# Generated by Django 3.2.5 on 2021-10-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0007_alter_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='course',
            field=models.ManyToManyField(to='swc.Course'),
        ),
    ]
