# Generated by Django 3.2.5 on 2021-10-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0008_participant_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField()),
                ('completion_result', models.CharField(max_length=50)),
                ('course', models.ManyToManyField(to='swc.Course')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='completion',
            field=models.ManyToManyField(to='swc.Completion_status'),
        ),
    ]
