# Generated by Django 3.2.5 on 2021-11-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0008_auto_20211101_0400'),
        ('swc', '0008_auto_20211101_1155'),
    ]

    operations = [
    ]
