# Generated by Django 3.2.5 on 2021-11-02 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0009_merge_0008_auto_20211101_0400_0008_auto_20211101_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion_status',
            name='commencement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 8, 48, 47, 507735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='completion_status',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 8, 48, 47, 507735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 8, 48, 47, 507735, tzinfo=utc)),
        ),
    ]
