# Generated by Django 3.2.5 on 2021-10-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0010_auto_20211016_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='industry',
            field=models.CharField(choices=[('M', 'MINING'), ('AG', 'AGRICULTURE'), ('MN', 'MINING'), ('MF', 'MANUFACTURING'), ('UT', 'UTILITIES'), ('CS', 'CONSTRUCTION'), ('AR', 'ARTS AND RECREATION'), ('HC', 'HEALTH CARE'), ('ED', 'EDUCATION AND TRAINING'), ('PS', 'PROFESSIONAL SERVICES'), ('RE', 'REAL ESTATE'), ('TA', 'TOURISM AND ACCOMMODATION'), ('IT', 'INFORMATION AND MEDIA'), ('OT', 'OTHER')], default='nul', max_length=50),
            preserve_default=False,
        ),
    ]
