# Generated by Django 3.2.5 on 2021-10-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0011_participant_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_reach', models.IntegerField()),
                ('participation_traget', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_industry',
            field=models.CharField(choices=[('M', 'MINING'), ('AG', 'AGRICULTURE'), ('MN', 'MINING'), ('MF', 'MANUFACTURING'), ('UT', 'UTILITIES'), ('CS', 'CONSTRUCTION'), ('AR', 'ARTS AND RECREATION'), ('HC', 'HEALTH CARE'), ('ED', 'EDUCATION AND TRAINING'), ('PS', 'PROFESSIONAL SERVICES'), ('RE', 'REAL ESTATE'), ('TA', 'TOURISM AND ACCOMMODATION'), ('IT', 'INFORMATION AND MEDIA'), ('OT', 'OTHER')], default='nul', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_why',
            field=models.CharField(default='2', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SponsorROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.IntegerField()),
                ('support_tech_women', models.IntegerField()),
                ('wider_tech_commitments', models.IntegerField()),
                ('sponsor', models.ManyToManyField(to='swc.Sponsors')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('better_equipped', models.IntegerField()),
                ('more_confident', models.IntegerField()),
                ('pursue_tech_career', models.IntegerField()),
                ('another_course', models.IntegerField()),
                ('interested_mentor', models.IntegerField()),
                ('course', models.ManyToManyField(to='swc.Course')),
                ('participant', models.ManyToManyField(to='swc.Participant')),
            ],
        ),
    ]
