# Generated by Django 3.2.5 on 2021-10-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0012_auto_20211023_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keystatistics',
            old_name='participation_traget',
            new_name='participation_target',
        ),
    ]
