# Generated by Django 3.2.5 on 2021-10-23 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0013_rename_participation_traget_keystatistics_participation_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantroi',
            name='participant',
        ),
        migrations.AddField(
            model_name='participantroi',
            name='participant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='swc.participant'),
            preserve_default=False,
        ),
    ]
