# Generated by Django 3.2.5 on 2021-10-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0014_auto_20211023_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion_status',
            name='course',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='completion',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='course',
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.completion_status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swc.participant')),
            ],
        ),
    ]
